#!/bin/ksh
#
#*****************************************************************************
#
# Name          Description                     Version Date
#
# Rob Dancer    Initial version			1.0     11 Nov 1997
#
# Rob Dancer    Changed "Exit OK" to "Exit"	1.1     17 Nov 1997
#
# Rob Dancer    Set return status correctly	1.2     18 Nov 1997
#
# Rob Dancer    References amended to           2.0     01 Dec 1997
#               "admintools"
#
# Rob Dancer    Changed spelling mistake	2.1     10 Dec 1997
#		"exits"
#
# Rob Dancer    Exit with variable not		2.2     18 Dec 1997
#		explicitly 0 when showing
#		version
#
# Rob Dancer    Add default -f FILE option	2.3     22 Apr 1998
#
# Rob Dancer    Change getopt to getopts	2.4     23 Apr 1998
#
# Rob Dancer    countitems			3.0     28 Apr 1998
#
# Rob Dancer    Put path in for ebbackup	3.1     29 Apr 1998
#
# Rob Dancer    Count inprogess			3.2     01 May 1998
#
VERSION="3.2, 01 May 1998"
#
#*****************************************************************************
#
# Exit function
#
function _exit {
 if [ -f $TMPFILE1 ]
 then
  rm $TMPFILE1
 fi
 exit $1
}
#
# Main function
#
function _Main {
#
# Insert user function here
#
DATE="`date '+%d/%m/%y'`"
TIME="`date '+%H:%M:%S'`"
if [ $USEEBFILE = "FALSE" ]
then
 /usr/epoch/EB/bin/ebbackup -L > $TMPFILE1
else
 cat $EBFILE > $TMPFILE1
fi
#
DATA=`cat $TMPFILE1 | $AWK 'BEGIN{
				 ITEMSLEFT=0
				 ITEMSINPROGRESS=0
				} {
				 WORD1=toupper($1)
				 WORD2=toupper($2)
				 if ( WORD1 == "WORKITEM" ) {
				  ITEMSLEFT=ITEMSLEFT+1
				 } else {
				  if ( WORD1 == "IN" && WORD2 == "PROGRESS" ) {
				   ITEMSINPROGRESS=ITEMSINPROGRESS+1
				  }
				 }
				} END {
				 printf "%s %s\n",ITEMSLEFT,ITEMSINPROGRESS
				}'`
#
echo "$DATE $TIME $DATA" >> $ITEMSFILE
#
#
# Set up return status
#
 RETSTAT=0
}
#
# Start here
#
#
# Source setup file
#
. /etc/admintools.src
SHOWVERSION="FALSE"
#
# Set up user variables
#
ITEMSDIR=$LOCALETC
FILE="itemcount.txt"
#ITEMSFILE=${ITEMSDIR}/${FILE}
ITEMSFILE=""
TMPFILE1="/tmp/tmpfile.$$"
EBFILE=""
USEEBFILE="FALSE"
#
#
# Initialise exit status
#
let "EXITSTAT=0"
#
# Get command line options
#
USAGE="$0 [-f file] [-e ebfile] [-V Version]"
while getopts f:e:V OPT
do
 case $OPT in
#
# Invalid option
#
        \?)
                if [ -z "$OPTARG" ]
                then
                 echo $USAGE
                 _exit 2
                fi
        ;;
#
# File
#
	f)
		ITEMSFILE=$OPTARG
	;;
#
# EB file
#
	e)
		EBFILE=$OPTARG
	;;
#
# Show version
#
	V)
		SHOWVERSION="TRUE"
	;;
 esac
done
#
# Check for show version
#
if [ "$SHOWVERSION" = "TRUE" ]
then
 echo "$VERSION"
 echo "$USAGE"
 _exit $EXITSTAT
fi
#
# Check EB file
#
if [ -z "$EBFILE" ]
then
 USEEBFILE="FALSE"
elif [ $EBFILE = "-" ]
then
 USEEBFILE="TRUE"
else
 if [ -r $EBFILE ]
 then
  USEEBFILE="TRUE"
 else
  echo "ERROR : Cannot open EB file $EBFILE"
  EXITSTAT="3"
  _exit $EXITSTAT
 fi
fi
#
# Do Main
#
_Main
let "EXITSTAT=EXITSTAT+RETSTAT"
#
# Exit
#
_exit $EXITSTAT
#
