#!/bin/ksh
#
#*****************************************************************************
#
# Name          Description                     Version Date
#
# Rob Dancer    Initial version			1.0     11 Nov 1997
#
# Rob Dancer    Changed "Exit OK" to "Exit"	1.1     17 Nov 1997
#
# Rob Dancer    Set return status correctly	1.2     18 Nov 1997
#
# Rob Dancer    References amended to           2.0     01 Dec 1997
#               "admintools"
#
# Rob Dancer    Changed spelling mistake	2.1     10 Dec 1997
#		"exits"
#
# Rob Dancer    Exit with variable not		2.2     18 Dec 1997
#		explicitly 0 when showing
#		version
#
# Rob Dancer    Add default -f FILE option	2.3     22 Apr 1998
#
# Rob Dancer    procglr				3.0     22 Apr 1998
#
# Rob Dancer    Removed outfile option		3.1     22 Apr 1998
#
# Rob Dancer    No temporary file needed	3.2     22 Apr 1998
#
# Rob Dancer    Extra field for sort		3.3     23 Apr 1998
#
# Rob Dancer    Add -u for sort in case there	3.4     24 Apr 1998
#		are suplicate fields
#
# Rob Dancer    Separate processing fields	3.5     28 Apr 1998
#
VERSION="3.5 28 Apr 1998"
#
#*****************************************************************************
#
# Exit function
#
function _exit {
 if [ -f "$TMPFILE1" ]
 then
  rm $TMPFILE1
 fi
 if [ -f "$TMPFILE2" ]
 then
  rm $TMPFILE2
 fi
 exit $1
}
#
# Main function
#
function _Main {
#
# Insert user function here
#
cat ${FILE} | sort -t "," -u \
 -k 1,1 -k 5,5 -k 2.7n,2.9 -k 2.4n,2.6 -k 2.1n,2.3 \
 -k 3.1n,3.3 -k 3.4n,3.6 -k 3.7n,3.9 -k 6,6| \
	 $AWK -F "," 'BEGIN{
			 NLINE="FALSE"
			} {
			 if ( $4 ~ "^Stop Item" ) {
			  print $0
			  print ""
			  NLINE="TRUE"
			 } else {
			  if ( $4 ~ "^Processing Item" ) {
			   if ( NLINE == "FALSE" ) {
			    print ""
			   } else {
			    NLINE="FALSE"
			   }
			   print $0
			  } else {
			   print $0
			  }
			 }
			}'
#
#
# Set up return status
#
 RETSTAT=0
}
#
# Start here
#
#
# Source setup file
#
. /etc/admintools.src
SHOWVERSION="FALSE"
#
# Set up user variables
#
TMPFILE1="/tmp/tmpfile1.$$"
FILE="-"
#
# Initialise exit status
#
let "EXITSTAT=0"
#
# Get command line options
#
USAGE="$0 [-f file] [-V Version]"
set -- `getopt f:V $*`
if [ $? -ne 0 ]
then
 echo $USAGE
_exit 2
fi
while [ $# -gt 0 ]
do
 case $1 in
#
# File
#
	-f)
		FILE=$2
		shift 2
	;;
#
# Show version
#
	-V)
		SHOWVERSION="TRUE"
		shift 1
	;;
	--)
		shift
		break
	;;
 esac
done
#
# Check for show version
#
if [ "$SHOWVERSION" = "TRUE" ]
then
 echo "$VERSION"
 echo "$USAGE"
 _exit $EXITSTAT
fi
#
# Check bounds of FILE
#
if [ -z "$FILE" ]
then
 echo "ERROR : Filename required"
 echo "$USAGE"
 EXITSTAT=2
 _exit $EXITSTAT
else
 if [ "$FILE" != "-" ]
 then
  if [ ! -r "$FILE" ]
  then
   echo "ERROR : File $FILE does not exist or cannot be opened"
   EXITSTAT=3
  _exit $EXITSTAT
  fi
 fi
fi
#
# Do Main
#
_Main
let "EXITSTAT=EXITSTAT+RETSTAT"
#
# Exit
#
_exit $EXITSTAT
#
